<?php
/**
 * Plugin Name: Caldera Entry Blocks
 * Description:
 * Version:     0.1.0
 * Author:
 * Author URI:
 * License:     GPL-2.0+
 * License URI: http://www.gnu.org/licenses/gpl-2.0.txt
 */

// Enqueue editor UI scripts & styles.
require_once( __DIR__ . '/inc/asset-loader.php' );
require_once( __DIR__ . '/inc/scripts.php' );
HMR_Demo\Scripts\setup();


add_action('caldera_forms_includes_complete', function () {
	class FormsRoute extends Caldera_Forms_API_Forms
	{
		public function prepare_form_for_response(Caldera_Forms_API_Form $form, WP_REST_Request $request)
		{
			return parent::prepare_form_for_response($form, $request); // TODO: Change the autogenerated stub
		}
	}

	add_filter('caldera_forms_api_js_config', function ($data) {
		$formsRoute = new FormsRoute();
		$request = new WP_REST_Request();
		$request->set_param('entry_list_only_fields', FALSE);
		$data[ 'forms' ] = [];
		$forms = Caldera_Forms_Forms::get_forms(FALSE, FALSE);
		foreach ( $forms as $form ) {
			$_form = new Caldera_Forms_API_Form(Caldera_Forms_Forms::get_form($form));
			$data[ 'forms' ][ $form ] = $formsRoute->prepare_form_for_response($_form, $request);
			if ( !empty($data[ 'forms' ][ $form ][ 'fields' ]) ) {
				$data[ 'forms' ][ $form ][ 'fields' ] = [];
			}
			$data[ 'forms' ][ $form ][ 'formId' ] = $form;
		}

		return $data;
	});
});
